apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-octant-testing
spec:
  vendor: eduk8s.io
  title: Testing out Octant
  description: Introduction and play area for testing Octant
  url: https://github.com/eduk8s-tests/lab-octant-testing
  image: quay.io/eduk8s-tests/lab-octant-testing:master
  session:
    ingress:
    - name: octant
