apiVersion: training.eduk8s.io/v1alpha1
kind: Workshop
metadata:
  name: lab-octant-testing
spec:
  vendor: eduk8s.io
  title: Octant Testing
  description: An introduction to Octant and play area for testing it
  url: https://github.com/eduk8s-labs/lab-octant-testing
  image: quay.io/eduk8s-labs/lab-octant-testing:master
  session:
    budget: medium
    applications:
      console:
        enabled: true
        vendor: octant
